### ISSUE TITLE
jQuery draggables --> unusable on touch devices

### ISSUE THREAD

**Issue by mickp** [MicronOxford/spectral-transmission#4]
jQuery draggables don't work with touch events, so this UI doesn't work on tablets or 'phones.
Can re-implement using jQuery touch punch UI, or use a more conventional check box for each filter (although this will probably only be practical if the filter list can be filtered).

**Comment by iandobbie** [comment]
However the preconfigured filter sets fix most of the issues. Not a major problem.

**Comment by iandobbie** [comment]
I think this is not a major issue and we should leave it as is. If you want to do full configuration then you need a computer, selecting existing filter configs then changing dye or excitation works fine. The optimise dye also works althougth the output window could be prettier.
